INSERT INTO rentals (location, price, date, group_size, type, rating, review, description, image1, image2, image3, image4, image5)
VALUES
 ('Florence, Indiana', 177, '2023-06-18', 3, 'trending', 4.5, 44, 'Experience the ultimate floating retreat with breathtaking views and luxurious amenities', 'https://i.imgur.com/rxBZAOn.png', 'https://i.imgur.com/AUTm8uL.png', 'https://i.imgur.com/Y7w6QPN.png', 'https://i.imgur.com/eeMBjFe.png', 'https://i.imgur.com/oNdFDCC.png'),
 ('Providence, Rhode Island', 230, '2023-08-20', 2, 'house-boat', 4.8, 33, 'Escape to a charming houseboat getaway, where tranquility meets adventure on the water', 'https://i.imgur.com/ka0OJU3.png', 'https://i.imgur.com/DcpdEmy.png', 'https://i.imgur.com/VcUpfiE.png', 'https://i.imgur.com/PYpmNvC.png', 'https://i.imgur.com/8PaVg1I.png'),
 ('Philadelphia, Pennsylvania', 390, '2023-06-22', 4, 'trending', 4.3, 23, 'Unwind in unrivaled splendor aboard a superyacht, where lavish interiors, panoramic views, and a dedicated crew ensure a truly unforgettable escape', 'https://i.imgur.com/CffFdCC.png', 'https://i.imgur.com/OIV3K8n.png', 'https://i.imgur.com/yVZm8hn.png', 'https://i.imgur.com/AhvHE4j.png', 'https://i.imgur.com/tkuxqso.png'),
 ('Racine, Wisconsin', 138, '2023-07-16', 3, 'sail-boat', 4.9, 15, 'Experience the freedom of the open sea as you sail on a beautifully crafted sailboat, with nothing but the horizon ahead', 'https://i.imgur.com/gOnSqjv.png', 'https://i.imgur.com/WGJtbiU.png', 'https://i.imgur.com/1cNhRp6.png', 'https://i.imgur.com/P43LEC1.png', 'https://i.imgur.com/A6nJ6GT.png'),
 ('Racine, Wisconsin', 135, '2023-07-16', 4, 'house-boat', 4.5, 12, 'Unwind and rejuvenate in a picturesque houseboat, where the gentle sway of the waves lulls you into a state of bliss', 'https://i.imgur.com/9Q6DV22.png', 'https://i.imgur.com/NB26X8q.png', 'https://i.imgur.com/WwxGOr6.png', 'https://i.imgur.com/2hWsJkc.png', 'https://i.imgur.com/xxHqOAN.png'),
 ('New Haven, Connecticut', 150, '2023-06-18', 7, 'house-boat', 4.7, 27, 'Experience a peaceful and idyllic retreat on a charming houseboat, where every sunrise and sunset is a work of art', 'https://i.imgur.com/OIqc4ug.png', 'https://i.imgur.com/AdCHRcX.png', 'https://i.imgur.com/ET39L0H.png', 'https://i.imgur.com/CIeTVU8.png', 'https://i.imgur.com/AfZMCmc.png'),
 ('Toms River, New Jersey', 250, '2023-07-09', 4, 'trending', 5.0, 4, 'Set sail on a romantic escapade aboard a luxurious sailboat, where gentle breezes and starry nights create the perfect ambiance', 'https://i.imgur.com/915xqQ1.png0', 'https://i.imgur.com/41uoUqf.png', 'https://i.imgur.com/yuox1q8.png', 'https://i.imgur.com/GhaiJmJ.png', 'https://i.imgur.com/AV9dmHD.png'),
 ('Brick Township, New Jersey', 165, '2023-06-25', 4, 'yacht', 4.9, 13, 'Escape to a world of sheer indulgence on a private yacht, where the only limit is your imagination and every desire is meticulously catered to', 'https://i.imgur.com/RN0RMFQ.png', 'https://i.imgur.com/GQK7XT6.png', 'https://i.imgur.com/EPFS3JS.png', 'https://i.imgur.com/ggjN4GO.png', 'https://i.imgur.com/0tK2ds0.png'),
 ('Key West, Florida', 140, '2023-08-20', 4, 'yacht', 4.2, 34, 'Immerse yourself in the lap of luxury on a magnificent yacht, where exquisite craftsmanship, sumptuous accommodations, and breathtaking views await', 'https://i.imgur.com/oSoSZGn.png', 'https://i.imgur.com/soKD49c.png', 'https://i.imgur.com/jAPJI5b.png', 'https://i.imgur.com/qkKswvL.png', 'https://i.imgur.com/fpPIGta.png'),
 ('Toronto, Canada', 128, '2023-06-25', 2, 'yacht',4.9, 44, 'Discover a floating paradise on a superyacht, where expansive decks, lavish amenities, and world-class service elevate your journey to new heights', 'https://i.imgur.com/x0oGmRP.png', 'https://i.imgur.com/kVbdqwj.png', 'https://i.imgur.com/VwCLTAl.png', 'https://i.imgur.com/5iqj8h6.png', 'https://i.imgur.com/3bfqCvI.png'),
 ('Miami, Florida', 300, '2023-06-23', 9, 'power-boat', 4.9, 33, 'Experience the adrenaline rush of water sports like never before on a powerful boat designed to unleash your inner thrill-seeker', 'https://i.imgur.com/uWnQiQx.png', 'https://i.imgur.com/skthcY7.png', 'https://i.imgur.com/cmDqfSS.png', 'https://i.imgur.com/PJyQ6OD.png', 'https://i.imgur.com/Sgn9IIC.png'),
 ('Fort Lauderdale, Florida', 360, '2023-06-23', 8, 'trending', 4.1, 32, 'Take your water sports adventures to new heights on a high-performance power boat built to conquer the waves and propel you to exhilarating speeds', 'https://i.imgur.com/y7hhHi0.png', 'https://i.imgur.com/68qPwfB.png', 'https://i.imgur.com/L5JB0F1.png', 'https://i.imgur.com/Pd0UiI4.png', 'https://i.imgur.com/xLglISP.png'),
 ('Boca Raton, Florida', 1095, '2023-06-23', 12, 'power-boat', 4.5, 30, 'Dive into a world of excitement and adventure as you carve through the water on a sleek power boat, perfect for wakeboarding, waterskiing, and tubing', 'https://i.imgur.com/SJbjFwb.jpg', 'https://i.imgur.com/ufNcDNM.png', 'https://i.imgur.com/L0Y09bk.png', 'https://i.imgur.com/lgLaZaX.png', 'https://i.imgur.com/4z0V1WW.png'),
 ('Sarasota, Florida', 140, '2023-06-23', 8, 'power-boat', 4.0, 31, 'Feel the exhilaration of pure speed as you race across the water on a sleek and powerful speed boat designed for adrenaline junkies', 'https://i.imgur.com/mbZVImW.jpg', 'https://i.imgur.com/AsKOduT.png', 'https://i.imgur.com/bbcuWXX.png', 'https://i.imgur.com/LXMNzCE.jpg', 'https://i.imgur.com/15yfoQv.png'),
 ('Miami Beach, Florida', 7223, '2023-06-23', 10, 'fishing-boat', 4.3, 35, 'Cast off on a fishing adventure aboard a versatile fishing boat, purposefully built to navigate various water conditions and equipped with modern conveniences to enhance your fishing endeavors', 'https://i.imgur.com/BDSlFFt.png', 'https://i.imgur.com/hjYiBnK.jpg', 'https://i.imgur.com/7YJkYtx.jpg', 'https://i.imgur.com/OjEalN9.jpg', 'https://i.imgur.com/u0dfsIJ.png'),
 ('Plaquemines Parish, Louisiana', 2800, '2023-06-23', 6, 'trending', 4.7, 76, '"Escape the ordinary and embark on a fishing journey on a meticulously crafted fishing boat, designed with the avid angler in mind, providing the perfect platform for successful and enjoyable fishing outings',  'https://i.imgur.com/BxC8f3y.png', 'https://i.imgur.com/Z5pbDhv.png', 'https://i.imgur.com/R1Gahqh.png', 'https://i.imgur.com/O8tv9X3.png', 'https://i.imgur.com/lFXiv4k.png'),
 ('Naples, Florida', 1800, '2023-06-23', 12, 'fishing-boat', 4.6, 24, 'Embark on a fishing expedition of a lifetime aboard a spacious and well-appointed fishing boat, offering all the amenities and tools necessary for a successful day on the water', 'https://i.imgur.com/7nTeDaK.png', 'https://i.imgur.com/o8zb4ks.png', 'https://i.imgur.com/QBelHRE.png', 'https://i.imgur.com/VspL1hU.png', 'https://i.imgur.com/R1Gahqh.png'),
 ('Cape Canaveral, Florida', 648, '2023-06-23', 12, 'fishing-boat', 5.0, 16, 'Experience the serenity of nature and the thrill of reeling in the big one on a fishing boat that combines comfort, stability, and exceptional fishing capabilities, ensuring an unforgettable fishing expedition',  'https://i.imgur.com/lLGb96k.jpg', 'https://i.imgur.com/CXbmy3n.jpg', 'https://i.imgur.com/E1zwEyU.jpg', 'https://i.imgur.com/4NaeAHL.jpg', 'https://i.imgur.com/OfRB7Ff.jpg'),
 ('Naples, Florida', 1155, '2023-06-23', 6, 'fishing-boat', 3.9, 17, 'Experience the thrill of the chase and the joy of reeling in trophy fish on a reliable and comfortable fishing boat, equipped with state-of-the-art fishing gear and technology', 'https://i.imgur.com/bPogrCl.png', 'https://i.imgur.com/6YEwvLk.png', 'https://i.imgur.com/KZiQd6J.png', 'https://i.imgur.com/k5WTe6j.png', 'https://i.imgur.com/brsK5Cl.png'),
 ('Naples, Florida', 1780, '2023-06-23', 20, 'sail-boat', 4.0, 21, 'Discover the art of sailing on a graceful sailboat, where skilled captains and pristine waters ensure an unforgettable maritime experience', 'https://i.imgur.com/1w1yPM6.png', 'https://i.imgur.com/IElkymn.png', 'https://i.imgur.com/lyZsLUY.png', 'https://i.imgur.com/JeOXY3C.png', 'https://i.imgur.com/JGiWpQA.png'),
 ('Key West, Florida', 2800, '2023-06-23', 12, 'sail-boat', 4.1, 30, 'Feel the thrill of harnessing the winds power as you navigate through pristine waters on a sleek and elegant sailboat', 'https://i.imgur.com/E4bqS6A.png', 'https://i.imgur.com/DvRFddJ.png', 'https://i.imgur.com/DdCjjTu.png', 'https://i.imgur.com/5G65riG.png', 'https://i.imgur.com/EFMh8ot.png'),
 ('Miami, Florida', 1100, '2023-06-23', 10, 'sail-boat', 4.3, 50, 'Experience the magic of a sailboat vacation, where every day brings a new coastal paradise and the promise of unforgettable memories',  'https://i.imgur.com/t21e2CR.png', 'https://i.imgur.com/aUHvrUC.png', 'https://i.imgur.com/KnrY3os.png', 'https://i.imgur.com/HCxlrGb.png', 'https://i.imgur.com/KZZCzVH.png'),
 ('Fort Lauderdale, Florida', 9000, '2023-06-23', 130, 'yacht', 4.6, 45, 'Unleash your inner explorer on a yacht charter, where hidden coves, vibrant marine life, and captivating destinations beckon you to chart your own course', 'https://i.imgur.com/ROoIhUn.png', 'https://i.imgur.com/rspcSeD.png', 'https://i.imgur.com/4raXStu.png', 'https://i.imgur.com/qobgVAc.png', 'https://i.imgur.com/A6Uh7Gp.png'),
 ('Edenton, North Carolina', 395, '2023-06-20', 7, 'house-boat', 4.8, 39, 'Stay in a floating oasis of tranquility, where the soothing sounds of nature create a symphony of relaxation', 'https://i.imgur.com/m0A1Rc2.png', 'https://i.imgur.com/lEzFM1T.png', 'https://i.imgur.com/7XIk9Qd.png', 'https://i.imgur.com/YAyDVUM.png', 'https://i.imgur.com/wstXzwQ.png');


